name: release
on: [push]
#on:
#  push:
#    tags:
#      - '*'
jobs:
  build:
    name: snapshot
    runs-on: ubuntu-latest
    steps:
      - run: pwd
      - run: find . -type f
      - run: make snapshot
