name: release
on: [push]
#on:
#  push:
#    tags:
#      - '*'
jobs:
  build:
    name: snapshot
    runs-on: ubuntu-latest
    steps:
      - run: pwd
        id: 1
      - run: find . -type f -print
        id: 2
      - run: make snapshot
        id: 3
