name: release
on: [push]
#on:
#  push:
#    tags:
#      - '*'
jobs:
  build:
    name: snapshot
    runs-on: ubuntu-latest
    steps:
      - run: pwd
        id: step1
      - run: /bin/ls -R1
        id: step2
      - run: -c make snapshot
        id: step3
