name: release
on: [push]
#on:
#  push:
#    tags:
#      - '*'
jobs:
  build:
    name: snapshot
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: checkout
        run: git fetch --prune --unshallow
      - name: ls
        run: /bin/ls -R1
      - name: snapshot
        run: make snapshot
